## Microware Docker Configuration for Magento
## (https://github.com/MagentoInstallationDOC/Microware-Projetos/)
##
## Version 1.0.0
## 


version: "3"

services:
  app:
    image: nginx:1.22
    ports:
      - "80:80"
    volumes: &appvolumes
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
    
  phpfpm:
    image: php:8.2-fpm
    volumes: *appvolumes
    env_file: env/phpfpm.env
   

  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.0.13
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  ## If you wish to use Elasticsearch, comment out opensearch image above and
  ## uncomment this block. Do the same in the composer.healthcheck.yaml file.
  # Additionally, if you are performing the manual setup, you will need to
  # update the bin/setup command to use the $ES_HOST variable as the value for
  # the --elasticsearch-host argument passed to bin/magento setup:install.
  #elasticsearch:
  #  image: markoshust/magento-elasticsearch:7.17-0
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"
  #  env_file: env/elasticsearch.env
  #  environment:
  #    - "discovery.type=single-node"
  #    ## Avoid test failures due to small disks
  #    ## More info at https://github.com/markshust/docker-magento/issues/488
  #    - "cluster.routing.allocation.disk.threshold_enabled=false"
  #    - "index.blocks.read_only_allow_delete"

  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env


volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  # sockdata:
  # ssldata:
